apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap-demo
  janus-idp.io/tekton: rhtap-demo
  backstage.io/kubernetes-id: rhtap-demo
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: rhtap-demo
resources: 
- deployment.yaml
- route.yaml
- service.yaml
